//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Nama { get; set; }
        public string Tgl_prod { get; set; }
        public string Shift { get; set; }
        public Nullable<int> Kode_prod { get; set; }
        public Nullable<int> Jumlah { get; set; }
    }
}
